In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
import imaplib
import email

In [12]:
with open("Sample Mails.txt",'r') as file:
    data = file.readlines()

X = []
Y = []
# dividing the data into message part and label part
for mail in data:
    mail_parts = mail.split('\t')
    label = mail_parts[0]
    message = ' '.join(mail_parts[1:])
    X.append(message)
    Y.append(label)

print(len(X))
print(len(Y))


20
20


In [13]:
print(X[0])

I want to visit Mauritius this summer so need to get some informations regarding the same. So what's the minimum tour package , whats services would I be provided in this package?, like all the complete details u can provide me.Regards.



In [14]:
tokenizer = RegexpTokenizer(r'\w+')
sw = set(stopwords.words('english'))
ss = SnowballStemmer("english")

In [15]:
def clean_mail(sentence):
    sentence = sentence.lower()
    sentence = sentence.replace("\n","")
    word_list = tokenizer.tokenize(sentence)
    word_list = [w for w in word_list if w not in sw]
    final_list = [ss.stem(w) for w in word_list]
    new_sentence = ' '.join(final_list)
    
    return new_sentence

In [16]:
X_clean = [clean_mail(i) for i in X]

In [17]:
print(len(X_clean))

20


In [18]:
print(X_clean[0])

want visit mauritius summer need get inform regard minimum tour packag what servic would provid packag like complet detail u provid regard


In [19]:
### Vectorization

In [20]:
cv = CountVectorizer(ngram_range=(1,2))
x_vec = cv.fit_transform(X_clean).toarray()

In [21]:
print(x_vec)
print(x_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(20, 1750)


In [22]:
print(cv.get_feature_names())

['00', '00 04', '00 deposit', '00 go', '00 money', '00 paid', '00 payment', '00 requir', '00 secur', '000', '000 00', '000 000', '000 300', '000 inr', '000 valid', '000 well', '001', '001 0922', '0096', '0096 8889', '04', '04 00', '04 20', '0922', '0922 swift', '10', '10 8036', '10 day', '10 engin', '100', '100 largest', '13', '13 000', '13 6000', '13 million', '13 snov', '1355853927873650', '1355853927873650 link', '14august', '14august gmail', '16', '16 https', '17', '17 https', '18', '18 https', '18 month', '1st', '1st 5th', '1st 7th', '1st march', '20', '20 gmt', '20 minut', '2017', '2017 happi', '2018', '2018 24', '2019', '2019 28th', '2019 4th', '2019 base', '2019 beconiitd', '2019 exclus', '2019 facilit', '2019 pleas', '2019 registr', '2019 rs', '2019 take', '20th', '20th februari', '2250814898', '2250814898 jxy6jcfnbpwc3zowneevnbe2wgcmuxw', '24', '24 wall', '250', '250 time', '28th', '28th februari', '2vnlvxe', '2vnlvxe 68mwc7', '30', '30 djs', '30 minut', '300', '300 colleg', 

In [23]:
def get_last_message():
    user = "gotravel.agsr@gmail.com"
    password = "AbhishekSachin"
    imap_url = "imap.googlemail.com"

    con = imaplib.IMAP4_SSL(imap_url)


    login = con.login(user,password)

    result,section_data = con.select('INBOX')
    number_of_mails = section_data[0].decode('utf-8')


    result,data = con.fetch(section_data[0],'(RFC822)') #section_data[0] = no. of mails so we would get the last mail.


    raw = email.message_from_bytes(data[0][1])
    message = raw.get_payload(0).get_payload(None,True)

    message = message.decode("utf-8")
    
    return message


In [24]:
message = get_last_message()
initial_message = message

In [25]:
message = clean_mail(message)
print(message)

packag visit india tourist place india


In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
mnb = MultinomialNB()
print(mnb)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [28]:
# Training 
mnb.fit(x_vec,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
message = [message]
message_vec = cv.transform(message)

In [30]:
print(mnb.predict(message_vec))

['ham']


In [31]:
prediction = mnb.predict(message_vec)
if prediction[0] == 'ham':
	print(initial_message)
else:
	ch = input("Message is spam. Do you want to see it? ->")
	if ch == 'y':
		print(initial_message)
	else:
		pass


What is the package for visiting India? and what are all the tourist places
in India?

